### ISSUE TITLE
Change the color

### ISSUE THREAD

**Issue by lakruzz** [Praqma/web-codeall#10]
Use the blue color suggested by Jonathan in the menu banner (and everywhere else it's needed)

**Comment by anetacamo** [comment]
There is a little issue with the blues :D

blue used in the logo is           #2cb1f8
blue used in the proposal is   #3b90cb   https://github.com/Praqma/phablework/issues/34
blue used in the banner is      #1daeec
there is also blue background behind the banner with different blue that is actually hidden behind the banner #2e7bcf - also the same color that the links have: #2e7bcf

Because, in my opinion, the blue in the logo would be hardest to change, I would stick with that blue that is a bit brighter  #2cb1f8 - and I was also thinking there is no need for the background image for the banner as long as we got the background color. So I will do that :)  

I will try to make the variable called §blue so it can be used easily everywhere!
